#! /bin/zsh
sudo npm init -y
sudo npm install --save-dev --unsafe-perm=true webpack
sudo npm install --save-dev --unsafe-perm=true style-loader css-loader
sudo npm install --save-dev --unsafe-perm=true -D postcss-loader
sudo npm install --save-dev --unsafe-perm=true sass-loader node-sass
sudo npm install --save-dev --unsafe-perm=true file-loader
sudo npm install --save-dev --unsafe-perm=true babel-loader babel-core babel-preset-env
sudo npm install --save-dev --unsafe-perm=true postcss-import
# 多页面应用，html 多出口，自动引入页面所需的 js 文件
sudo npm install --save-dev --unsafe-perm=true html-webpack-plugin
# sudo npm install --save-dev --unsafe-perm=true jquery